---

- hosts: controller
  gather_facts: true
  tasks:
    - name: Tagged packages
      ansible.builtin.command:
        chdir: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
        cmd: >-
          ansible-playbook deploy-edpm.yml
          -e @scenarios/centos-9/base.yml
          -e @scenarios/centos-9/install_yamls.yml
          -e @scenarios/centos-9/ci.yml
          -e @scenarios/centos-9/zuul_inventory.yml
          {%- if cifmw_extras is defined %}
          {%-   for extra_vars in cifmw_extras %}
          -e "{{   extra_vars }}"
          {%-   endfor %}
          {%- endif %}
          --tags packages
    - name: Tagged bootstrap - no packages
      ansible.builtin.command:
        chdir: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
        cmd: >-
          ansible-playbook deploy-edpm.yml
          -e @scenarios/centos-9/base.yml
          -e @scenarios/centos-9/install_yamls.yml
          -e @scenarios/centos-9/ci.yml
          -e @scenarios/centos-9/zuul_inventory.yml
          {%- if cifmw_extras is defined %}
          {%-   for extra_vars in cifmw_extras %}
          -e "{{   extra_vars }}"
          {%-   endfor %}
          {%- endif %}
          --tags bootstrap
          --skip-tags packages
    - name: Not tagged bootstrap nor packages
      ansible.builtin.command:
        chdir: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
        cmd: >-
          ansible-playbook deploy-edpm.yml
          -e @scenarios/centos-9/base.yml
          -e @scenarios/centos-9/install_yamls.yml
          -e @scenarios/centos-9/ci.yml
          -e @scenarios/centos-9/zuul_inventory.yml
          {%- if cifmw_extras is defined %}
          {%-   for extra_vars in cifmw_extras %}
          -e "{{   extra_vars }}"
          {%-   endfor %}
          {%- endif %}
          --skip-tags bootstrap,packages
