- hosts: controller
  gather_facts: true
  tasks:
    - name: Run kuttl tests playbook
      ansible.builtin.command:
        chdir: "{{ ansible_user_dir }}/src/github.com/openstack-k8s-operators/ci-framework"
        cmd: >-
          ansible-playbook ci/playbooks/kuttl/e2e-kuttl.yml
          -e @scenarios/centos-9/base.yml
          -e @scenarios/centos-9/ci.yml
          -e @scenarios/centos-9/kuttl.yml
          -e @scenarios/centos-9/zuul_inventory.yml
